# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    todo: ignore
    unused_element: ignore
    unused_import: ignore
    unused_local_variable: ignore
    depend_on_referenced_packages: ignore
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    use_build_context_synchronously: ignore
    dangling_library_doc_comments: ignore
    unnecessary_brace_in_string_interps: ignore
    avoid_types_as_parameter_names: ignore
  exclude:
    - lib/features/_help_disabled/**
    - lib/**/_help_disabled/**
    - lib/features/_help_disabled/**/*
    - lib/features/_help_disabled/**.dart
    # Safety Fund feature canceled - exclude from analysis
    - lib/features/safety_fund/**
    # Messaging demos/widgets still evolving - exclude from strict analysis
    - lib/widgets/messaging/**
    - lib/services/messaging/**
    - lib/services/messaging_initializer.dart
    - lib/models/messaging/**/generated/**
    # Exclude generated Data Connect files from linting
    - lib/dataconnect_generated/**
    - lib/features/profile/presentation/pages/profile_*_test.dart
    - lib/features/profile/presentation/pages/profile_test_page.dart
    - lib/features/profile/presentation/pages/profile_network_test_page.dart
    - lib/**/profile_*_test_page.dart
    # Ensure profile test page is excluded regardless of path separator or folder changes
    - lib/**/profile_test_page.dart
    # Exclude ad-hoc analysis/test scripts that are not part of production app code
    - test_runner.dart
    - "**/test_*.dart"
    - test_firestore.dart
    - test_integration_test.dart
    - full_app_functionality_test.dart
    - comprehensive_app_functionality_analysis.dart
    - comprehensive_functionality_analysis.dart
    # Exclude legacy or standalone scripts at repo root
    - check_sar_entitlement.dart
    - debug_sar_access.dart
    - emergency_call_isolation_test.dart
    - sar_access_verification_test.dart
    - sar_system_validation.dart
    - sar_access_demo.dart
    - run_network_analysis.dart
    - run_subscription_analysis.dart
    - update_subscription.dart
    - query_help_requests.dart
    - mark_help_requests_resolved.dart
    - mark_sos_sessions_resolved.dart
    - setup_sar_user.dart
    - hardware_diagnostics.dart
    # Exclude integration and messaging tests not maintained currently
    - integration_test/**
    - test/messaging/**
    - test_scripts/**

linter:
  # The lint rules applied to this project can be customized in the
  # section below to disable rules from the `package:flutter_lints/flutter.yaml`
  # included above or to enable additional rules. A list of all available lints
  # and their documentation is published at https://dart.dev/lints.
  #
  # Instead of disabling a lint rule for the entire project in the
  # section below, it can also be suppressed for a single line of code
  # or a specific dart file by using the `// ignore: name_of_lint` and
  # `// ignore_for_file: name_of_lint` syntax on the line or in the file
  # producing the lint.
  rules:
    avoid_print: false  # Disable `avoid_print` globally (many bench/test utilities print)
    # prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
