// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbfJvjgDxGZ21no8NSVLcQkXf7GTJf4ec',
    appId: '1:557287609270:web:3bd44b87fdf7a324832717',
    messagingSenderId: '557287609270',
    projectId: 'redping-a2e37',
    authDomain: 'redping-a2e37.firebaseapp.com',
    storageBucket: 'redping-a2e37.firebasestorage.app',
    measurementId: 'G-DDN5Y1DDN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBJhW4EHzPwzfxuauXSB1k30w_rTml6Po',
    appId: '1:557287609270:android:ee97c332c47695a6832717',
    messagingSenderId: '557287609270',
    projectId: 'redping-a2e37',
    storageBucket: 'redping-a2e37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVkOTdQRI0VJLRPQi-WP3LOKmcm-jvzLM',
    appId: '1:557287609270:ios:602b31ccfe961d72832717',
    messagingSenderId: '557287609270',
    projectId: 'redping-a2e37',
    storageBucket: 'redping-a2e37.firebasestorage.app',
    iosBundleId: 'com.example.redping14v',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVkOTdQRI0VJLRPQi-WP3LOKmcm-jvzLM',
    appId: '1:557287609270:ios:602b31ccfe961d72832717',
    messagingSenderId: '557287609270',
    projectId: 'redping-a2e37',
    storageBucket: 'redping-a2e37.firebasestorage.app',
    iosBundleId: 'com.example.redping14v',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbfJvjgDxGZ21no8NSVLcQkXf7GTJf4ec',
    appId: '1:557287609270:web:3776ed57820899ce832717',
    messagingSenderId: '557287609270',
    projectId: 'redping-a2e37',
    authDomain: 'redping-a2e37.firebaseapp.com',
    storageBucket: 'redping-a2e37.firebasestorage.app',
    measurementId: 'G-XJH5G21ZEC',
  );

}